apiVersion: v1
kind: Service
metadata:
{{- if lower .Values.sename}}
  name: {{lower .Values.name}}-{{ lower .Values.sename}}-svc
{{- else }}
  name: {{ lower .Values.name}}-svc
{{- end }}
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 4000
    protocol: TCP
  selector:
  {{- if lower .Values.sename }}
    app: {{lower .Values.name}}-{{lower .Values.sename}}
  {{- else }}
    app: {{lower .Values.name}}
 {{- end }}